# Find full documentation here https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
name: CI

on:
  pull_request:

  # Manual invocation.
  workflow_dispatch:

  push:
    branches:
      - main
jobs:
  CI:
    name: Build project files and upload
    runs-on: ubuntu-latest

    permissions:
      # required by aws-actions/configure-aws-credentials
      id-token: write
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Upload secure-drop-monitor to riff-raff
        uses: guardian/actions-riff-raff@v4
        with:
          roleArn: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          app: monitor
          configPath: secure-drop-monitor-riff-raff.yaml
          projectName: InfoSec::secure-drop
          contentDirectories: |
            secure-drop-monitor-cloudformation:
              - cloudformation/secure-contact.template.yaml
